#!/usr/bin/env php

<?php

require __DIR__ . '/vendor/autoload.php';

use BapCat\Persist\Drivers\Filesystem\FilesystemDriver;
use BapCat\Tailor\Tailor;
use BapCat\Tailor\PersistTemplateFinder;
use BapCat\Tailor\Compilers\PhpCompiler;

// Grab filesystem directories
$persist = new FilesystemDriver(__DIR__ . '/storage');
$templates = $persist->get('templates');
$compiled  = $persist->get('compiled');

// TemplateFinders are able to find and use raw/compiled templates
$finder = new PersistTemplateFinder($templates, $compiled);

// Compilers translate raw templates into compiled ones
$compiler = new PhpCompiler();

// Create an instance of Tailor to actually do the autoloading
$tailor = new Tailor($finder, $compiler);

$test = new ASDD;
var_dump($test);
